// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW4K2MzRVY532J094tGzzErhaH1cIdzsU',
    appId: '1:286730004317:web:dbd83ebcbad2a0041eaab4',
    messagingSenderId: '286730004317',
    projectId: 'pushnoti-bcb84',
    authDomain: 'pushnoti-bcb84.firebaseapp.com',
    storageBucket: 'pushnoti-bcb84.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_6f8JCceLEIyULAwX3hyUKLFI6JHhiGE',
    appId: '1:286730004317:android:45216cc780fe9bc81eaab4',
    messagingSenderId: '286730004317',
    projectId: 'pushnoti-bcb84',
    storageBucket: 'pushnoti-bcb84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxiqiUBKo1YVQ5MaMnWJNMONXIUF7R6fc',
    appId: '1:286730004317:ios:69c215c6ad769fb91eaab4',
    messagingSenderId: '286730004317',
    projectId: 'pushnoti-bcb84',
    storageBucket: 'pushnoti-bcb84.firebasestorage.app',
    iosBundleId: 'com.example.pushnoti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxiqiUBKo1YVQ5MaMnWJNMONXIUF7R6fc',
    appId: '1:286730004317:ios:69c215c6ad769fb91eaab4',
    messagingSenderId: '286730004317',
    projectId: 'pushnoti-bcb84',
    storageBucket: 'pushnoti-bcb84.firebasestorage.app',
    iosBundleId: 'com.example.pushnoti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW4K2MzRVY532J094tGzzErhaH1cIdzsU',
    appId: '1:286730004317:web:27194702b35c71b81eaab4',
    messagingSenderId: '286730004317',
    projectId: 'pushnoti-bcb84',
    authDomain: 'pushnoti-bcb84.firebaseapp.com',
    storageBucket: 'pushnoti-bcb84.firebasestorage.app',
  );
}
